export const FETCH_VIDEOS_SUCCESS="FETCH_VIDEOS_SUCCESS";
export const FETCH_VIDEOS_SUCCESS_SAGA="FETCH_VIDEOS_SUCCESS_SAGA";
export const PREVIOUSLY_VIDEOS="PREVIOUSLY_VIDEOS" ;
export const PREVIOUSLY_VIDEOS_SAGA="PREVIOUSLY_VIDEOS" ;
export const HISTORY_SAGA="HISTORY";
export const HISTORY="HISTORY";

